[[Eurac]]
=== Eurac Research

// Please provide content under the headlines given below. Please delete the instructions. At the bottom, you find some instructions on ASCIIDOC.

// Please provide the name of all people you would like to have included in the list of contributing authors on top, following the pattern below:
//Ingo Simonis | OGC
 - Armin Costa (armin.costa@eurac.edu) | Eurac Research | 
 - Alexander Jacob (alexander.jacob@eurac.edu)| Eurac Research

==== Motivation to Participate
// please describe briefly why you participated

We are striving after development of interoperable research independent of cloud processing facilities to foster exchange and repeatability. In particular the Institute for Earth Observation at EURAC Research has the need to be able to run transparently applications on different clusters, where data and computing resources are available.
The proposed hackathon was perfectly in line with what we currently try to achieve in the in the *H2020 openEO project* ( http://openeo.eu ), where we are already developing a driver to connect the *openEO API* with the *OGC WC(P)S 2.0* and it processing extension. So participating in this hackathon gave as the possibility to implement and test web processing services based on processing chains organized in containers and link it to the RESTful services that we are currently defining and developing in the *openEO* project.

==== Implemented Solution
// please describe your implemented solution here. Provide as much detail as you think reasonable.



The solution implemented by *Eurac Research* consists of an ADES server that exposes a set of operations as describend in the *OGC Testbeds*, in form of a set of *WPS 1.0.0* compliant operation offerings.
Further an interface with the *openEO API* has been started to be implemented to access those web process services in a RESTful way and render it interoperable with the client API's in *python* and *R* that are currently in development.

The reasons to use WPS 1.0.0 for the implementation are:

- To ensure compatibility with the tools currently employed (i.e GeoServer)
- To ensure compatibility with a larger set of available libraries and tools available
- Have a general, lightweight model that can be easily trasfered also to WPS 2.0.0 in near future


The operations actually implemented as a proof of concept and working prototype are the following:

- **DeployProcess**
- **ExecuteProcess**
- **UndeployProcess**
- **GetStatus**
- Get Result (not yet fully implemented)

Those processes are also discoverable via openEO using the /processes endpoint of the RESTful API. 



The GetCapabilites result for the service (wpseoproc) implemented:
[source,xml]
----
	<wps:ProcessOfferings>
		<wps:Process wps:processVersion="1.0.0">
			<ows:Identifier>gs:DeployProcessEO</ows:Identifier>
			<ows:Title>DeployProcess</ows:Title>
			<ows:Abstract>DeployProcess Operation EURAC Research EO</ows:Abstract>
		</wps:Process>
		<wps:Process wps:processVersion="1.0.0">
			<ows:Identifier>gs:ExecuteProcessEO</ows:Identifier>
			<ows:Title>ExecuteProcess</ows:Title>
			<ows:Abstract>ExecuteProcess Operation EURAC Research EO</ows:Abstract>
		</wps:Process>
		<wps:Process wps:processVersion="1.0.0">
			<ows:Identifier>gs:GetResultEO</ows:Identifier>
			<ows:Title>GetResult</ows:Title>
			<ows:Abstract>GetResult Operation of Process EURAC Research EO</ows:Abstract>
		</wps:Process>
		<wps:Process wps:processVersion="1.0.0">
			<ows:Identifier>gs:GetStatusEO</ows:Identifier>
			<ows:Title>StatusInfo</ows:Title>
			<ows:Abstract>StatusInfo Operation of Process EURAC Research EO</ows:Abstract>
		</wps:Process>
		<wps:Process wps:processVersion="1.0.0">
			<ows:Identifier>gs:UndeployProcessEO</ows:Identifier>
			<ows:Title>UndeployProcess</ows:Title>
			<ows:Abstract>UndeployProcess Operation EURAC Research EO</ows:Abstract>
		</wps:Process>
	</wps:ProcessOfferings>
----


The implementation uses the proposed OWS Context Document (OWC) to describe and deploy an application. This seems a very good standard and convenient way to convey and validate the application capabilities on a given cluster.

The OWC document is passed as parameter to the WPS **DeployProcess** operation offering.

The ADES server, appart exposing the listed WPS services, will also perform the following tasks:

- Store and manage all application related information found in the OWS context Document in a persistent database
- Evaluate and execute the offerings defined in the OWC document, in particular owc offerings related to pulling a given container from the repository, executing a given OpenSearch Query on a given catalogue (optional), and executing the defined wpsProcessOffering
- Upon the **ExecuteProcess** operation, the ADES will also perform the "Staging" operation on the data referenced, i.e Download the data in a local process defined workskpace, which in our imlementation is defined as $ApplicationRunStore. The staging is performed based on the policies defined in the ProcessParameters (sections -> cloud:.., data:...) and considers, if any defined, the results of the search offering defined in the OWC document. Also the configuration defined in the 'data:" section of the ProcessParameters are evaulated and translated to data references --> this allows actually on one side the application developer to have a defined dataset which is forseen to work with the application, and also allows the user eventually to provide  a paricular or even different dataset, of course only if this is validated also by the OWC document definitions (i.e. </georss:where>, <dc:date>)





### DeployProcess


The DeployProcess operation allows to deploy a process defined as an Application OWS Context document (OWC) and has the following Parameters:

**Request:**

- **OWC** : ATOM-encoded OWS Context Document describing the application package
- **Options**: Control Options (clusterURI=...., etc..)

**Response:**

- **StatusInfo**: Status of the depployment operation. If successfull contains a <ows:Identifier..> tag with the Process UUID  


DescribeProcess result:
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<wps:ProcessDescriptions xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:wps="http://www.opengis.net/wps/1.0.0"
	xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xml:lang="en" service="WPS" version="1.0.0"
	xsi:schemaLocation="http://www.opengis.net/wps/1.0.0 http://schemas.opengis.net/wps/1.0.0/wpsAll.xsd">
	<ProcessDescription wps:processVersion="1.0.0"
		statusSupported="true" storeSupported="true">
		<ows:Identifier>gs:DeployProcessEO</ows:Identifier>
		<ows:Title>DeployProcess</ows:Title>
		<ows:Abstract>DeployProcess Operation EURAC Research EO</ows:Abstract>
		<DataInputs>
			<Input maxOccurs="1" minOccurs="1">
				<ows:Identifier>OWC</ows:Identifier>
				<ows:Title>OWC</ows:Title>
				<ows:Abstract>An ATOM-encoded OWS Context Document describing the application package</ows:Abstract>
				<ComplexData maximumMegabytes="4">
					<Default>
						<Format>
							<MimeType>application/atom+xml</MimeType>
						</Format>
					</Default>
					<Supported>
						<Format>
							<MimeType>application/atom+xml</MimeType>
						</Format>
						<Format>
							<MimeType>application/xml</MimeType>
						</Format>
						<Format>
							<MimeType>text/xml</MimeType>
						</Format>
					</Supported>
				</ComplexData>
			</Input>
			<Input maxOccurs="1" minOccurs="1">
				<ows:Identifier>Options</ows:Identifier>
				<ows:Title>Options</ows:Title>
				<ows:Abstract>Control Options</ows:Abstract>
				<LiteralData>
					<ows:AnyValue />
				</LiteralData>
			</Input>
		</DataInputs>
		<ProcessOutputs>
			<Output>
				<ows:Identifier>DeployResponse</ows:Identifier>
				<ows:Title>DeployResponse</ows:Title>
				<ComplexOutput>
					<Default>
						<Format>
							<MimeType>text/xml</MimeType>
						</Format>
					</Default>
					<Supported>
						<Format>
							<MimeType>text/xml</MimeType>
						</Format>
					</Supported>
				</ComplexOutput>
			</Output>
		</ProcessOutputs>
	</ProcessDescription>
</wps:ProcessDescriptions>
----

The ProcessIdentifier UUID returned, if valid, is usable for subsequent ExecuteProcess and UndeployProcess operations



### ExecuteProcess


Once an application has been deployed and a valid UUID ProcessIdentifier is available, the ExecuteProcess operation allows to execute the applicaction by means of additional, process specific parameters defined in a JSON format.


The parameters for the operation are the following:

**Request:**

- **ProcessInstanceIdentifier:** Identifier of the process instance to be executed (UUID)
- **ProcessParameters:** Parameters for the Process in JSON format
- **Options:** Control Options (mode=sync|async, etc..)

The ProcessParameters are organized in the following sections and contain a defined set of switches and configurations applicable to a process:

- **cloud:** Cloud specific parameters (ex. Amount of requested resources, Maximum amount to be spent, Timeout policy for killing a process, Scheduler used, etc.)
- **container:** Parameters which are specific to a given environment where the process is intended to be run (eg. docker, kubernetes, Apache Hadoop, etc..). 
- **application:** Parameters specific to the application deployed inside a container, which in the simplest general case is the path to a standard Application entry point (e.g ../run.sh script)
- **data:** List of data references passed to the application. If null, the data referece is adopted by the results of the OpenSearch offering in the OWC document (code=http://www.opengis.net/spec/owc-atom/1.0/opensearch). This can be a list of 1 - n Files or URLs.

This is a sample for the ProcessParameters: 
**ProcessParameters:**
[source,json]
----
{
	"cloud":"ncpu=4, environment=docker, exec_policy=parallel",
	"container":"-t --rm -v $ApplicationRunStore:/home/adesuser/data/ -e INPUT_IMAGE=$Data",
	"application":"/home/adesuser/processing_scripts/run.sh",
	"data":"S2B_MSIL1C_20180417T102019_N0206_R065_T32TPP_20180417T140522.zip"
}
----
Both variables $ApplicationRunStore and $Data are possible placeholders and are replaced at runtime by the ADES application.

The variable **$ApplicationRunStore** is a path placeholder and consists in this case of the dedicated working directory assigned automatically by the ADES to a given process instance.

The variable **$Data** is a placeholder for the data referenced by the user, or by a search offering operation defined in the OWC document (code=http://www.opengis.net/spec/owc-atom/1.0/opensearch)

The Parameters are validated by the ADES before executing the process

If the request is validated and executed sucessfully the response includes an indentifier of the job executed (JobID)

**Response:**

- **StatusInfo** Execute Response with Status and JobID elements

e.g Response (WPS 2.0)
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<wps:StatusInfo xmlns:wps="http://www.opengis.net/wps/2.0"
	xmlns:atom="http://www.w3.org/2005/Atom" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.opengis.net/wps/2.0 ../wps.xsd">
	<wps:JobID>809963556</wps:JobID>
	<wps:Status>Running</wps:Status>
	<atom:link rel="monitor"
		href="http://saocompute.eurac.edu/wpseoproc/jobs/809963556" />
	<atom:link rel="cancel"
		href="http://saocompute.eurac.edu/wpseoproc/jobs/cancel/809963556" />
</wps:StatusInfo>
----


In the case where a process is executed in parallel on a larger set of files, the response includes a list of JobIDs. This is convenient so that a GetStatus($JobID) operation can be executed on each single child process.




==== Proposed Alternatives
// if you have any recommendations on other solutions, please describe them here



==== Experiences with AP & ADES
// please describe your experiences with the Application Package and the Application Deployment and Execution Service here.

==== Other Impressions & Recommendations
// whatever other impressions, recommendations etc. you have, please put them here


