[[VITO]]
=== VITO

// Please provide content under the headlines given below. Please delete the instructions. At the bottom, you find some instructions on ASCIIDOC.

// Please provide the name of all people you would like to have included in the list of contributing authors on top, following the pattern below:
Jeroen Dries | VITO

==== Motivation to Participate
* VITO operates the PROBA-V Exploitation Platform
* VITO is a potential provider of application packages
* VITO is a potential user of application packages
* VITO participates in the OpenEO project which has similar/complementary goals.

==== Implemented Solution
https://github.com/VitoTAP/ADES
// please describe your implemented solution here. Provide as much detail as you think reasonable.
1. Deployment of simplified application package (https://github.com/VitoTAP/ADES/blob/master/resources/executeDeploy.xml)
2. Direct execution of arbitrary command in arbitrary docker image, no deploy needed (https://github.com/VitoTAP/ADES/blob/master/resources/executeDocker.xml)
3. Deployment of a full WPS packaged as Docker container. Kubernetes was used as a scalable/multi-cloud container orchestrator. https://github.com/VitoTAP/ADES/tree/master/microservice

==== Proposed Alternatives
Solution 2 is my preferred solution, as the deployment step can be replaced by uploading the image to a Docker registry (which can still be a customized marketplace for remote sensing related images). Standardization will be limited to specifying the generic docker run process itself. Most existing WPS's already support this type of custom process, without modifying the WPS itself.
The spec of the generic process can also be made fairly foolproof, as there is no need to have a command line template, clients should just specify the command line directly.

==== Experiences with AP & ADES
* OWS Context based AP had a relatively steep learning curve, partially because the OWS Context standard is not written with the AP in mind.
* A lot of implementations made the assumption that the deployed process should be invoked with a filename. In this case, parallelization can be achieved by the client sending multiple requests in parallel. 
* Parallelization on the WPS side, by sending a list of files for instance, is not supported by the standard. However, processes packaged inside docker containers also can not really parallelize themselves, as it depends on the distributed processing system that is available to the ADES. Not sure if it is desirable to have this in the standard, as sending multiple requests on the client side is also relatively simple.

==== Other Impressions & Recommendations
* Refactor the AP to a simplified XML document that has an optional OWS Context document rather than the being an OWS Context. (Basically use composition over inheritance.) This ensure that simple client/server implementations can be written more easily, while more advanced implementations can still show a COP if desirable.


